### PR TITLE
WIP: Defaults initialization in build()

### PR DESCRIPTION
**Pull request by mo8it**
WIP

### CODE REVIEW

**Comment by mo8it** [comment]
I was very excited and started to work on this crate, but I did just find out that what this crate does and what I wanted to complete is already done in [typed-builder](https://github.com/idanarye/rust-typed-builder). Well, one could say I have wasted a day, but I will take it as an exercise! I did indeed learn a lot while planing this.

I will probably even make a blog post about it because understanding what happens here is an awesome demonstration of compile time magic!

Anyway, this was my plan:

```rust
#[derive(Debug)]
pub struct Foo<'a, T: std::fmt::Debug> {
    bar: &'a T,
    baz: i32,
    opt: Option<u8>,
}

#[must_use]
pub struct FooBuilder<'a, T: std::fmt::Debug, FieldBar, FieldBaz, FieldOpt> {
    inner: core::mem::MaybeUninit<Foo<'a, T>>,
    fields: core::marker::PhantomData<(FieldBar, FieldBaz, FieldOpt)>,
}

impl<'a, T: std::fmt::Debug> Foo<'a, T> {
    pub fn builder() -> FooBuilder<
        'a,
        T,
        FooBuilderFields::BarUnset,
        FooBuilderFields::BazUnset,
        FooBuilderFields::OptUnset,
    > {
        FooBuilder {
            inner: core::mem::MaybeUninit::uninit(),
            fields: core::marker::PhantomData,
        }
    }
}

impl<'a, T: std::fmt::Debug, FieldBaz, FieldOpt>
    FooBuilder<'a, T, FooBuilderFields::BarUnset, FieldBaz, FieldOpt>
{
    pub fn set_bar(
        mut self,
        value: &'a T,
    ) -> FooBuilder<'a, T, FooBuilderFields::BarSet, FieldBaz, FieldOpt> {
        let inner = self.inner.as_mut_ptr();
        unsafe {
            core::ptr::addr_of_mut!((*inner).bar).write(value);
        }

        unsafe { core::mem::transmute(self) }
    }
}

impl<'a, T: std::fmt::Debug, FieldBar, FieldOpt>
    FooBuilder<'a, T, FieldBar, FooBuilderFields::BazUnset, FieldOpt>
{
    pub fn set_baz(
        mut self,
        value: i32,
    ) -> FooBuilder<'a, T, FieldBar, FooBuilderFields::BazSet, FieldOpt> {
        let inner = self.inner.as_mut_ptr();
        unsafe {
            core::ptr::addr_of_mut!((*inner).baz).write(value);
        }

        unsafe { core::mem::transmute(self) }
    }
}

impl<'a, T: std::fmt::Debug, FieldBar, FieldBaz>
    FooBuilder<'a, T, FieldBar, FieldBaz, FooBuilderFields::OptUnset>
{
    pub fn set_opt(
        mut self,
        value: Option<u8>,
    ) -> FooBuilder<'a, T, FieldBar, FieldBaz, FooBuilderFields::OptSet> {
        let inner = self.inner.as_mut_ptr();
        unsafe {
            core::ptr::addr_of_mut!((*inner).opt).write(value);
        }

        unsafe { core::mem::transmute(self) }
    }
}

impl<
        'a,
        T: std::fmt::Debug,
        FieldBaz: FooBuilderFields::BazDefault<'a, T>,
        FieldOpt: FooBuilderFields::OptDefault<'a, T>,
    > FooBuilder<'a, T, FooBuilderFields::BarSet, FieldBaz, FieldOpt>
{
    #[must_use]
    pub fn build(mut self) -> Foo<'a, T> {
        let inner = self.inner.as_mut_ptr();
        FieldBaz::default_if_not_set(inner);
        FieldOpt::default_if_not_set(inner);

        unsafe { self.unsafe_build() }
    }
}

impl<'a, T: std::fmt::Debug, FieldBar, FieldBaz, FieldOpt>
    FooBuilder<'a, T, FieldBar, FieldBaz, FieldOpt>
{
    #[must_use]
    pub unsafe fn unsafe_build(self) -> Foo<'a, T> {
        self.inner.assume_init()
    }
}

mod FooBuilderFields {
    use super::*;

    pub struct BarSet;
    pub struct BarUnset;

    pub struct BazSet;
    pub struct BazUnset;
    pub trait BazDefault<'a, T: std::fmt::Debug> {
        fn default_if_not_set(_inner: *mut Foo<'a, T>) {}
    }
    impl<'a, T: std::fmt::Debug> BazDefault<'a, T> for BazSet {}
    impl<'a, T: std::fmt::Debug> BazDefault<'a, T> for BazUnset {
        fn default_if_not_set(inner: *mut Foo<'a, T>) {
            unsafe {
                core::ptr::addr_of_mut!((*inner).baz).write(42);
            }
        }
    }

    pub struct OptSet;
    pub struct OptUnset;
    pub trait OptDefault<'a, T: std::fmt::Debug> {
        fn default_if_not_set(_inner: *mut Foo<'a, T>) {}
    }
    impl<'a, T: std::fmt::Debug> OptDefault<'a, T> for OptSet {}
    impl<'a, T: std::fmt::Debug> OptDefault<'a, T> for OptUnset {
        fn default_if_not_set(inner: *mut Foo<'a, T>) {
            unsafe {
                core::ptr::addr_of_mut!((*inner).opt).write(core::default::Default::default());
            }
        }
    }
}

fn main() {
    let foo = Foo::builder()
        .set_bar(&"OK")
        .set_baz(8)
        .set_opt(Some(12))
        .build();
    dbg!(foo);
}
```

The most important thing I wanted to achieve is initialization of defaults in `build` if they are not set. Not already in `builder` to be replaced later when set.

I don't see a value in me ending this. I would suggest closing this PR and linking to typed-builder in the README instead? @estebank

**Comment by estebank** [comment]
I think the difference between this and typed-builder (besides the fact that the later is probably more production-ready) is that uses `MemUninit` to avoid an intermediary representation of the builder: this constructs the value in-place at all times, it uses type casting shenanigans to get the final fully initialized type. I think typed-builder creates a separate type (need to confirm) that holds all of the optional values as `Option<T>` and during building it copies each field one by one.

**Comment by mo8it** [comment]
typed-builder doesn't use an Option. It stores the fields directly in a struct and creates new ones for new values.

I will try to reproduce it in an example and benchmark that.

**Comment by mo8it** [comment]
@estebank @idanarye

I have done benchmarks with surprising results!

Benchmarking command:

```fish
cargo b -r && hyperfine -N -m 100 "./target/release/BINARY"
```

# Typed-Builder

```rust
struct Foo<'a, T: std::fmt::Debug> {
    bar: &'a T,
    baz: i32,
}

impl<'a, T: std::fmt::Debug> Foo<'a, T> {
    fn builder() -> FooBuilder<'a, T, ((), ())> {
        FooBuilder {
            fields: ((), ()),
            phantom: Default::default(),
        }
    }
}

struct FooBuilder<'a, T: std::fmt::Debug, TypedBuilderFields = ((), ())> {
    fields: TypedBuilderFields,
    phantom: (
        core::marker::PhantomData<&'a ()>,
        core::marker::PhantomData<T>,
    ),
}

pub trait FooBuilder_Optional<T> {
    fn into_value<F: FnOnce() -> T>(self, default: F) -> T;
}

impl<T> FooBuilder_Optional<T> for () {
    fn into_value<F: FnOnce() -> T>(self, default: F) -> T {
        default()
    }
}

impl<T> FooBuilder_Optional<T> for (T,) {
    fn into_value<F: FnOnce() -> T>(self, default: F) -> T {
        self.0
    }
}

impl<'a, T: std::fmt::Debug, __baz> FooBuilder<'a, T, ((), __baz)> {
    pub fn bar(self, bar: &'a T) -> FooBuilder<'a, T, ((&'a T,), __baz)> {
        let bar = (bar,);
        let (_, baz) = self.fields;
        FooBuilder {
            fields: (bar, baz),
            phantom: self.phantom,
        }
    }
}

impl<'a, T: std::fmt::Debug, __bar> FooBuilder<'a, T, (__bar, ())> {
    pub fn baz(self, baz: i32) -> FooBuilder<'a, T, (__bar, (i32,))> {
        let baz = (baz,);
        let (bar, _) = self.fields;
        FooBuilder {
            fields: (bar, baz),
            phantom: self.phantom,
        }
    }
}

impl<'a, T: std::fmt::Debug, __baz: FooBuilder_Optional<i32>> FooBuilder<'a, T, ((&'a T,), __baz)> {
    pub fn build(self) -> Foo<'a, T> {
        let (bar, baz) = self.fields;
        let bar = bar.0;
        let baz = FooBuilder_Optional::into_value(baz, || 42);
        Foo { bar, baz }.into()
    }
}

fn main() {
    for _ in 0..1_000_000_000 {
        std::hint::black_box(Foo::builder().bar(&"OK").baz(42).build());
    }
}
```

## Results

```
Time (mean ± σ):     356.9 ms ± 119.2 ms    [User: 355.7 ms, System: 0.4 ms]
Range (min … max):   229.4 ms … 495.9 ms    100 runs
```

# Makeit

```rust
pub struct Foo<'a, T: std::fmt::Debug> {
    bar: &'a T,
    baz: i32,
}

#[must_use]
pub struct FooBuilder<'a, T: std::fmt::Debug, FieldBar, FieldBaz> {
    inner: core::mem::MaybeUninit<Foo<'a, T>>,
    fields: core::marker::PhantomData<(FieldBar, FieldBaz)>,
}

impl<'a, T: std::fmt::Debug> Foo<'a, T> {
    pub fn builder() -> FooBuilder<'a, T, FooBuilderFields::BarUnset, FooBuilderFields::BazUnset> {
        FooBuilder {
            inner: core::mem::MaybeUninit::uninit(),
            fields: core::marker::PhantomData,
        }
    }
}

impl<'a, T: std::fmt::Debug, FieldBaz> FooBuilder<'a, T, FooBuilderFields::BarUnset, FieldBaz> {
    pub fn set_bar(
        mut self,
        value: &'a T,
    ) -> FooBuilder<'a, T, FooBuilderFields::BarSet, FieldBaz> {
        let inner = self.inner.as_mut_ptr();
        unsafe {
            core::ptr::addr_of_mut!((*inner).bar).write(value);
        }

        unsafe { core::mem::transmute(self) }
    }
}

impl<'a, T: std::fmt::Debug, FieldBar> FooBuilder<'a, T, FieldBar, FooBuilderFields::BazUnset> {
    pub fn set_baz(mut self, value: i32) -> FooBuilder<'a, T, FieldBar, FooBuilderFields::BazSet> {
        let inner = self.inner.as_mut_ptr();
        unsafe {
            core::ptr::addr_of_mut!((*inner).baz).write(value);
        }

        unsafe { core::mem::transmute(self) }
    }
}

impl<'a, T: std::fmt::Debug, FieldBaz: FooBuilderFields::BazDefault<'a, T>>
    FooBuilder<'a, T, FooBuilderFields::BarSet, FieldBaz>
{
    #[must_use]
    pub fn build(mut self) -> Foo<'a, T> {
        let inner = self.inner.as_mut_ptr();
        FieldBaz::default_if_not_set(inner);

        unsafe { self.unsafe_build() }
    }
}

impl<'a, T: std::fmt::Debug, FieldBar, FieldBaz> FooBuilder<'a, T, FieldBar, FieldBaz> {
    #[must_use]
    pub unsafe fn unsafe_build(self) -> Foo<'a, T> {
        self.inner.assume_init()
    }
}

mod FooBuilderFields {
    use super::*;

    pub struct BarSet;
    pub struct BarUnset;

    pub struct BazSet;
    pub struct BazUnset;
    pub trait BazDefault<'a, T: std::fmt::Debug> {
        fn default_if_not_set(_inner: *mut Foo<'a, T>) {}
    }
    impl<'a, T: std::fmt::Debug> BazDefault<'a, T> for BazSet {}
    impl<'a, T: std::fmt::Debug> BazDefault<'a, T> for BazUnset {
        fn default_if_not_set(inner: *mut Foo<'a, T>) {
            unsafe {
                core::ptr::addr_of_mut!((*inner).baz).write(42);
            }
        }
    }
}

fn main() {
    for _ in 0..1_000_000_000 {
        std::hint::black_box(Foo::builder().set_bar(&"OK").set_baz(42).build());
    }
}
```

## Results

```
Time (mean ± σ):     493.9 ms ±   6.8 ms    [User: 491.8 ms, System: 0.7 ms]
Range (min … max):   483.6 ms … 516.9 ms    100 runs
```

# What?

Typed-Builder seems to be faster although Makeit uses unsafe `MaybeUninit` without building new structs! How?

**Comment by orowith2os** [comment]
> Typed-Builder seems to be faster although Makeit uses unsafe

Unsafe doesn't always mean faster. It just gives you more features that you might be able to use to squeeze out the maximum amount of performance, like inline assembly. 

The safe Rust code could very well be optimized inside of the compiler to something more efficient than the unsafe code, which lets you handle all of that.

**Comment by idanarye** [comment]
`MaybeUninit` skips checks and does not need a tag, so it **can** be faster than `Option` (assuming whatever you do to replace the checks and the tag is not worse than just using an `Option`), but nothing beats compile time (maybe except JIT)

As humans, we can reason that the generic parameters of makeit's builder type indicate the initialization status of the `MaybeUninit`, but this seems like a very hard connection for the compiler to make. Modern compilers are very smart, but using `transmute` to mutate individual fields of the inner value seems like something that would be extremely hard for a compiler to reason about. I'm not sure `MaybeUninit` was even supposed to be used like that (partial initialization of individual fields while the value as a whole is still considered uninitialized)

In Typed Builder, the generic parameter that indicates which fields have been initialized is _directly_ connected to how their value is stored - the compiler knows how it works, and can easily optimizer it. Typed Builder creates and destroys structs, yes, but it's all immutable - so once the compiler inlines everything it can easily collapse the assignment chains all the way into a direct construction of the target type. It's very optimizable.

**Pull request closed without merging**
